baseURL = "https://caravansinaustralia.com/"
languageCode = "en-us"
title = "Best Caravans In Australia"
theme = "directorytheme"
publishdir = "public"
paginate =  10

[taxonomies]
    tag = "tags"
    category = "categories"

[menu]

	[[menu.main]]
		identifier = "Guide"
		name = "2023 Caravan Guide"
		url = "/ultimate-caravan-guide/"
		weight = 5
	[[menu.main]]
		identifier = "Blog"
		name = "Blog"
		url = "/blog/"
		weight = 10

[related]
  includeNewer = true
  threshold = 80
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[params]
  copyrighthtml = "* NOTE: This website not affiliated with Caravans Australia or any governing body."
  tagslimit = 10
  GAnalytics = "UA-XXXXXXXX-XX"
  GTag = "UA-XXXXXXXX-XX"
  GoogleSiteVerify = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  MailChimpLink = "https://ukturingscheme.us7.list-manage.com/subscribe/post?u=076448fea24ee29988369fe2c&amp;id=700d18fbb4"
  MailChimpBot = "b_076448fea24ee29988369fe2c_700d18fbb4"	
  MetaDescription = "Find the best caravans in Melbourne, best caravans in Sydney, best caravans in Brisbane, best caravans in Adelaide, best caravans in Hobart, best caravans in Darwin, best caravans in Perth all rated in one place!"
